### PR TITLE
update formidable to use version 1.1.1

### PR DESCRIPTION
**Pull request by chrisgh1**
See following issue for discussion on error:
Buffer.write(string, encoding, offset[, length]) is no longer supported
https://github.com/yaronn/wcf.js/issues/16

maybe even would consider changing to ^1.1.1

### CODE REVIEW

**Comment by santiperez** [comment]
I also faced this issue. Is there any plan to accept this pull request and publish a new version of this module? Now Node version LTS is v6.11.4.

Thanks in advance.

Regards

**Comment by TinoSM** [comment]
For those waiting, meanwhile you can use npm-shrinkwrap to override the dependency to override the dependency, it's working fine on my end

`
    "ws.js": {
      "version": "2.0.22",
      "dependencies": {
        "formidable": {
          "version": "1.1.1",
          "resolved": "..../formidable-1.1.1.tgz",
          "integrity": "sha1-lriIb3w8NQi5Mta9cMTTqI818ak="
        }
      }
    }`

**Comment by yaronn** [comment]
hi, sorry for the delay, I've published ws.js@2.0.23 with this fix.

**Comment by santiperez** [comment]
👍 Thanks @yaronn 

Regards.

**Pull request merged**
